name: release
on:
  release:
    types: [published]

permissions:
    contents: write

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Build rbxm and release
        run: |
          rojo build -o build.rbxm
          gh release upload ${{github.event.release.tag_name}} build.rbxm